base: hm3d_00217
filepath: 
  - "/checkpoint/notmahi/data/hm3d_semantic/data/versioned_data/hm3d-1.0/hm3d/train/00217-qz3829g1Lzf/qz3829g1Lzf.basis.glb"
grid_size: 10
image_size: 512
subsample_prob: 0.2
