base: hm3d_00217
filepath: 
  - "/checkpoint/notmahi/data/hm3d_semantic/data/versioned_data/hm3d-1.0/hm3d/train/00217-qz3829g1Lzf/qz3829g1Lzf.basis.glb"
grid_size: 10
image_size: 512
subsample_prob: 0.2

semantic_class_remapping: {
    "other": "otherprop", 
    "unknown": "otherprop", 
    "armchair": "chair", 
    "attic door": "door", 
    "bag": "bag", 
    "bascet": "container",
    "basket": "container", 
    "basket of something": "basket",
    "bath utensil": "otherprop",
    "bathroom accessory": "otherprop",
    "bed": "bed",
    "bed table": "nightstand", 
    "bedside table": "nightstand", 
    "beside table": "nightstand", 
    "blinds": "blinds", 
    "book": "books", 
    "bowl": "container",
    "box": "box", 
    "box of tissue": "box", 
    "box of tissues": "box", 
    "brush": "otherprop", 
    "cabinet": "cabinet", 
    "candel": "candle", 
    "candle holder": "candle", 
    "cat bed": "bed", 
    "ceiling": "ceiling", 
    "ceiling ": "ceiling", 
    "ceiling lamp": "lamp", 
    "ceiling vent": "vent", 
    "chair": "chair", 
    "chandelier": "lamp", 
    "clock": "otherprop", 
    "closet mirror wall": "mirror", 
    "clothes hanger rod": "curtain", 
    "coffee machine": "kitchen appliance", 
    "coffee table": "table", 
    "computer desk": "desk", 
    "computer mouse": "mouse", 
    "couch": "sofa", 
    "curtain": "curtain", 
    "curtain rod": "curtain", 
    "decoration": "otherprop", 
    "decorative plant": "otherprop", 
    "desk": "desk", 
    "desk lamp": "lamp", 
    "diploma": "paper", 
    "dishwasher": "kitchen appliance", 
    "door": "door", 
    "door frame": "door", 
    "doorframe ": "door", 
    "dresser": "dresser", 
    "electrical controller": "otherprop", 
    "fan": "refrigerator",
    "fireplace": "refrigerator", 
    "floor": "floor", 
    "floor lamp": "lamp", 
    "floor mat": "floormat", 
    "floor vent": "floor", 
    "flower": "lamp", 
    "folding chair": "chair", 
    "footrest": "chair", 
    "handrail": "wall", 
    "keyboard": "desk", 
    "kitchen appliance": "kitchen appliance", 
    "kitchen cabinet": "cabinet", 
    "kitchen decoration": "bookshelf", 
    "kitchen shelf": "shelves", 
    "lamp": "lamp", 
    "led tv": "television", 
    "lmap": "lamp", 
    "microwave": "kitchen appliance", 
    "mirror": "mirror", 
    "mirror ": "mirror", 
    "mirror frame": "mirror", 
    "monitor": "television", 
    "night table": "nightstand", 
    "oven": "kitchen appliance", 
    "painting": "paper", 
    "paper towel": "towel", 
    "picture": "picture", 
    "pillow": "pillow", 
    "plate": "desk", 
    "pouffe": "dresser", 
    "printer": "paper", 
    "rack": "shelves", 
    "radio": "television",
    "refrigerator": "refrigerator", 
    "sensor": "lamp", 
    "shelf": "shelves", 
    "shoe": "otherprop", 
    "shower curtain": "curtain", 
    "sink": "sink", 
    "small table": "table", 
    "sofa chair": "sofa", 
    "stairs": "floor", 
    "stand": "chair", 
    "storage box": "box", 
    "table": "table", 
    "tablecloth": "table", 
    "tap": "sink", 
    "throw blanket": "sofa", 
    "tissue box": "box", 
    "toilet": "toilet", 
    "toilet paper": "toilet", 
    "toilet paper dispenser": "toilet", 
    "towel": "towel", 
    "towel bar": "towel", 
    "toy": "pillow", 
    "trash bin": "bag", 
    "tv stand": "bookshelf", 
    "unknwom": "otherfurniture", 
    "unknwon": "otherfurniture", 
    "vacuum cleaner": "kitchen appliance", 
    "vase": "otherprop",
    "vese": "otherprop", 
    "wal": "wall", 
    "wall": "wall", 
    "wall ": "wall", 
    "wall cabinet": "cabinet", 
    "wall clock": "wall", 
    "wall electronics": "wall", 
    "wall hanging decoration": "lamp", 
    "wall lamp": "lamp", 
    "wall toilet paper": "toilet", 
    "wall vent": "wall", 
    "wardrobe": "dresser", 
    "window": "window", 
    "window ": "window", 
    "window curtain": "curtain", 
    "window frame": "window", 
    "windown frame": "window", 
    "windows frame": "window", 
    "office chair": "chair", 
    "bookshelf": "bookshelf", 
    "clothes": "clothes", 
    "tv": "television", 
    "nightstand": "nightstand", 
    "counter": "counter", 
    "stool": "chair", 
    "cushion": "sofa", 
    "plant": "otherprop", 
    "bathtub": "bathtub", 
    "end table": "table", 
    "dining table": "table", 
    "backpack": "bag", 
    "whiteboard": "whiteboard", 
    "blanket": "pillow", 
    "trash can": "bag", 
    "closet": "dresser", 
    "stove": "kitchen appliance", 
    "computer tower": "computer", 
    "bottle": "bottle", 
    "bin": "container", 
    "ottoman": "sofa", 
    "bench": "chair", 
    "board": "whiteboard", 
    "washing machine": "bathtub", 
    "copier": "paper", 
    "file cabinet": "cabinet", 
    "laptop": "computer", 
    "shower": "showercurtain", 
    "paper": "paper", 
    "person": "person", 
    "paper towel dispenser": "towel", 
    "blackboard": "whiteboard", 
    "piano": "desk", 
    "suitcase": "bag", 
    "rail": "wall", 
    "radiator": "vent", 
    "recycling bin": "container", 
    "container": "container", 
    "soap dispenser": "toilet", 
    "telephone": "otherprop", 
    "bucket": "container", 
    "light": "lamp", 
    "laundry basket": "container", 
    "pipe": "toilet", 
    "clothes dryer": "dresser", 
    "guitar": "otherprop", 
    "toilet paper holder": "toilet", 
    "seat": "chair", 
    "speaker": "otherprop", 
    "column": "wall", 
    "bicycle": "otherprop", 
    "ladder": "ceiling", 
    "bathroom stall": "toilet", 
    "shower wall": "wall", 
    "cup": "container", 
    "jacket": "clothes", 
    "storage bin": "container", 
    "coffee maker": "kitchen appliance", 
    "paper towel roll": "towel", 
    "machine": "otherprop", 
    "mat": "floormat", 
    "windowsill": "window", 
    "bar": "counter", 
    "toaster": "kitchen appliance", 
    "bulletin board": "whiteboard", 
    "ironing board": "dresser", 
    "soap dish": "bathtub", 
    "kitchen counter": "counter", 
    "doorframe": "door", 
    "mini fridge": "refrigerator", 
    "fire extinguisher": "otherprop",
    "ball": "otherprop",
    "hat": "clothes", 
    "shower curtain rod": "curtain",
    "water cooler": "refrigerator",
    "paper cutter": "otherprop",
    "tray": "desk",
    "shower door": "door",
    "pillar": "wall",
    "ledge": "wall",
    "toaster oven": "kitchen appliance",
    "mouse": "lamp",
    "toilet seat cover dispenser": "toilet",
    "furniture": "otherfurniture",
    "cart": "shelves",
    "storage container": "container",
    "scale": "floormat", 
    "light switch": "otherprop",
    "crate": "box",
    "power outlet": "otherprop",
    "sign": "otherprop",
    "projector": "otherprop",
    "closet door": "door",
    "candle": "candle",
    "plunger": "toilet",
    "stuffed animal": "pillow",
    "headphones": "otherprop",
    "dish rack": "kitchen appliance", 
    "broom": "otherprop",
    "guitar case": "bag",
    "range hood": "kitchen appliance",
    "dustpan": "otherprop",
    "hair dryer": "otherprop", 
    "water bottle": "container",
    "handicap bar": "chair", 
    "purse": "bag",
    "vent": "vent",
    "shower floor": "floor",
    "water pitcher": "otherprop", 
    "mailbox": "box", 
    "paper bag": "bag", 
    "alarm clock": "nightstand", 
    "music stand": "bookshelf",
    "projector screen": "wall",
    "divider": "wall",
    "laundry detergent": "otherprop",
    "bathroom counter": "counter",
    "object": "otherprop",
    "bathroom vanity": "mirror",
    "closet wall": "wall", 
    "laundry hamper": "dresser",
    "bathroom stall door": "door", 
    "ceiling light": "lamp", 
    "dumbbell": "otherprop",
    "stair rail": "wall",
    "tube": "container", 
    "bathroom cabinet": "cabinet",
    "cd case": "box",
    "closet rod": "dresser",
    "coffee kettle": "kitchen appliance",
    "structure": "cabinet",
    "shower head": "showercurtain",
    "keyboard piano": "otherprop",
    "case of water bottles": "box",
    "coat rack": "shelves",
    "storage organizer": "container",
    "folded chair": "chair", 
    "fire alarm": "otherprop",
    "power strip": "lamp",
    "calendar": "counter",
    "poster": "paper",
    "potted plant": "otherprop",
    "luggage": "bag",
    "mattress": "bed",
}