_target_: models.view_encoders.masked_timm_view_encoder.MaskedTimmViewEncoder
view_shape:
  - ${image_size}
  - ${image_size}
timm_class: resnet34
semantic_embedding_len: 10
# TODO Mahi figure out the true number of semantic classes.
num_semantic_classes: 256
device: ${device}
representation_length: ${representation_dim}
use_fourier_features: false
