scene_transformer:
  _target_: models.basic_feedforward.Feedforward
  representation_dim: ${representation_dim}
  device: ${device}
  scene_model:
    _target_: utils.mlp.MLP
    input_dim: 3
    hidden_dim: 512
    output_dim: ${representation_dim}
    hidden_depth: 4
    batchnorm: True
