scene_transformer:
  _target_: models.scene_transformer.SceneTransformer
  representation_dim: ${representation_dim}
  device: ${device}
  mask_prob: 0.5
  pos_mask_prob: 0.5
  scene_model:
    _target_: utils.mlp.MLP
    input_dim: ${representation_dim}
    hidden_dim: 512
    output_dim: ${representation_dim}
    hidden_depth: 2
    batchnorm: True
