_target_: models.task_decoders.fourier_pixel_location_conv.FourierPixelLocationConvDecoder
representation_length: ${representation_dim}
depth: 3
hidden_dim: 256
batchnorm: True
device: ${device}
lam: 10.0
