_target_: models.task_decoders.pixel_location_conv_large.PixelLocationConvLargeDecoder
representation_length: ${representation_dim}
depth: 3
hidden_dim: 256
batchnorm: True
device: ${device}
lam: 10.0
